# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[workspace]
members = [
  "cli",
  "core",
  "runtime",
  "test_plugin",
  "test_util",
  "op_crates/fetch",
  "op_crates/web",
  "op_crates/crypto"
]
exclude = [
  "std/hash/_wasm"
]
